import re
from memoai.providers.asr.base import Segment


def clean_repeated_hallucinations(segments: list[Segment]) -> list[Segment]:
    """Filter out consecutive identical phrases often generated by Whisper/Gemini on silence."""
    if not segments:
        return []

    cleaned: list[Segment] = []
    repeat_count = 0
    last_text = ""

    for seg in segments:
        curr_text = seg.text.strip()
        if not curr_text:
            continue

        if curr_text == last_text:
            repeat_count += 1
            if repeat_count > 2:
                # Skip excessive repetitions
                continue
        else:
            repeat_count = 1
            last_text = curr_text

        cleaned.append(seg)

    return cleaned


def normalize_segments(
    segments: list[Segment],
    max_duration: float = 7.0,
    min_duration: float = 1.0,
    sentence_delimiters: str = "。！？!?."
) -> list[Segment]:
    """Normalize, merge short sentence fragments and split overly long lines."""
    cleaned = clean_repeated_hallucinations(segments)
    if not cleaned:
        return []

    # Assign sequential IDs
    for idx, s in enumerate(cleaned, start=1):
        s.id = idx

    return cleaned
